image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/kubeflow
  tag: latest
  pullPolicy: IfNotPresent

component:
  name: eks-curso-kubeflow
  command: ["python", "main.py"]
  args: []

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

nodeSelector: {}
tolerations: []
affinity: {}