AWSTemplateFormatVersion: 2010-09-09
Description: EKS cluster

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  Vpc:
    Type: AWS::EC2::VPC::Id
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  Subnet3:
    Type: AWS::EC2::Subnet::Id
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/eks/optimized-ami/1.32/amazon-linux-2/recommended/image_id

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chat-memory
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: SessionId
          AttributeType: S
        - AttributeName: MessageTime
          AttributeType: S
      KeySchema:
        - AttributeName: SessionId
          KeyType: HASH
        - AttributeName: MessageTime
          KeyType: RANGE

  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: eks-curso
      RoleArn: !GetAtt ClusterRole.Arn
      Version: 1.32
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !Ref SecurityGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS cluster security group
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: 80
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref Cluster
      NodeRole: !GetAtt NodeGroupRole.Arn
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 2
        MinSize: 2
      InstanceTypes:
        - t3.medium
      AmiType: AL2_x86_64
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2

  NodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
        - arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy
      Policies:
      - PolicyName: load-balancers
        PolicyDocument:
          Version: "2008-10-17"
          Statement:
          - Effect: Allow
            Action:
              - elasticloadbalancing:*
              - ec2:*
              - shield:GetSubscriptionState
            Resource:
              - '*'
      Path: /
