version: '3.2'
services:
  dashboard:
    image: office-simulation:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8501"
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ./:/app/
    command: ["streamlit", "run", "main.py"]