apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component.name }}
  labels:
    app: {{ .Values.component.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.component.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.component.name }}
    spec:
      containers:
        - name: {{ .Values.component.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.component.command }}
          args: {{ toJson .Values.component.args }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}