replicaCount: 1

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11433

resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

nodeSelector:
  eks.amazonaws.com/nodegroup: ollama-models

tolerations: []

affinity: {}