apiVersion: v1
kind: Application
metadata:
  name: api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: HEAD
    path: charts/argo-workflow
    helm:
      valueFiles:
        - api/api.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true