apiVersion: v1
kind: Service
metadata:
  name: s3-uploader-service
spec:
  selector:
    app: s3-uploader
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer  # or ClusterIP if using Ingress