apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aip3-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/gusalvarado/practicas.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true