apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ollama-server
  template:
    metadata:
      labels:
        app: ollama-server
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 11433
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ollama-data
          emptyDir: {}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}