apiVersion: v1
kind: Service
metadata:
  name: ollama-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11433
      protocol: TCP
      name: http
  selector:
    app: ollama-server